
version: '2'

services:
  cron:
    restart: always
    environment:
      - BACKUP_ENABLED
      - DB_NAME
      - DB_CONTAINER
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_ROOT}/pgbackup.sh:/etc/periodic/${BACKUP_PERIOD}/pgbackup.sh
      - ${APP_ROOT}/Makefile:/root/Makefile
    stop_signal: SIGKILL
    pull_policy: never
    image: $DCAPE_COMPOSE
    command: crond -f -d 8
